name: react-native-android-build-apk
on:
  push:
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.0.0"

      - name: Restore Npm Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          yarn

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Rename Apk Name 
        run: cp android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/v2hub-${{ steps.get_version.outputs.VERSION }}.apk

      - name: build changelog
        id: build_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".config/changelog_configuration.json"
          ignorePreReleases: "false"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          files:  |
            android/app/build/outputs/apk/release/v2hub-${{ steps.get_version.outputs.VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release.apk
      #     path: android/app/build/outputs/apk/release/


  jishida-push:
    runs-on: ubuntu-latest
    needs: [build-android]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: JiShiDa Push
        uses: funnyzak/jishida-action@master
        with:
          key: ${{secrets.JPUSH_KEY}}
          head: ${{github.repository}}已完成打包发布
          body: 来自GithubAction：${{github.repository}} 发布已完成，下载地址：https://github.com/funnyzak/react-native-v2ex/releases。
